name: Release in Play Store using different method

on:
  workflow_dispatch:
    inputs:
      release_notes:
        description: 'Release Notes'
        required: true

jobs:
  determine_trigger_branch_or_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate with Google Cloud
        run: |
          echo "${{ secrets.PLAYSTORE_ACCOUNT_KEY }}" > service-account.json
          gcloud auth activate-service-account --key-file=service-account.json
      - name: Get Edit ID
        id: get_edit_id
        run: |
          # Authenticate with Google Play Developer API
          ACCESS_TOKEN=$(gcloud auth print-access-token)
          
          # Make a request to list edits for the given package name
          RESPONSE=$(curl -X GET \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            "https://www.googleapis.com/androidpublisher/v3/applications/com.mobiletesting.testapp/edits")
          
          # Extract the edit ID from the response
          EDIT_ID=$(echo "$RESPONSE" | jq -r '.edits[0].id')
          echo "Edit ID: $EDIT_ID"
