name: Release in Play Store via another method

on:
  workflow_dispatch:
    inputs:
      release_notes:
        description: 'Release Notes'
        required: true


jobs:
  determine_edit_id:
    runs-on: ubuntu-latest
    steps:
      - name: Get Edit ID
        id: get_edit_id
        run: |
          RESPONSE=$(curl -X GET \
            -H "Authorization: Bearer ${{ secrets.PLAYSTORE_ACCOUNT_KEY }}" \
            "https://www.googleapis.com/androidpublisher/v3/applications/com.mobiletesting.testapp/edits?packageName=com.mobiletesting.testapp")
          echo "API Response: $RESPONSE"
          EDIT_ID=$(echo "$RESPONSE" | jq -r '.edits[0].id')
          echo "Edit ID: $EDIT_ID"
