name: Release in Play Store using different method

on:
  workflow_dispatch:
    inputs:
      release_notes:
        description: 'Release Notes'
        required: true

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

    

      - name: Check if pubspec.yaml exists
        run: |
          if [ -f "./whatsnew/whatsnew-en-USi.txt" ]; then
            echo "whatsnew-en-US.txt exists"
          else
            echo "whatsnew-en-US.txt does not exist"
            exit 1
          fi
      - name: List files in repository
        run: ls -R

