on:
  workflow_dispatch:
    inputs:
      release_notes:
        description: 'Release Notes'
        required: true

# Define the name of this workflow
name: "Release app in Playstore via fastlane"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build release APK
        run: ./gradlew assembleRelease # Adjust your build command
        
      - name: Get latest release info
        id: latest_release
        uses: actions/github-script@v5
        with:
          script: |
            const response = await github.rest.repos.getLatestRelease({
              owner: 'SathanaV-Software-Engineer',
              repo: 'luminator_testing'
            });

            console.log('Latest release:', response.data);

            // Extract the asset details of the AAB file from the latest release
            const assetDetails = response.data.assets.find(asset => asset.name === 'app-release.aab');

            console.log('Asset details:', assetDetails.browser_download_url);
            
            // Set the assetDetails as an output
            console.log(`::set-output name=assetDetails::${assetDetails.browser_download_url}`);
      - name: Download release file
        run: |
          wget -O app-release.aab "${{ steps.latest_release.outputs.assetDetails }}"
          



      - name: Deploy to Google Play Store
        uses: docker://fastlane/fastlane:latest
        with:
          args: supply --track internal --package_name com.mobiletesting.testapp --aab app-release.aab --json_key_data "$secrets.GOOGLE_PLAY_JSON"
        env:
          GOOGLE_PLAY_JSON: ${{ secrets.GOOGLE_PLAY_JSON }}
