name: Release in Play Store using different method

on:
  workflow_dispatch:
    inputs:
      release_notes:
        description: 'Release Notes'
        required: true

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List files in repository
        run: ls -R

      - name: Check if pubspec.yaml exists
        run: |
          if [ -f "pubspec.yaml" ]; then
            echo "pubspec.yaml exists"
          else
            echo "pubspec.yaml does not exist"
            exit 1
          fi

