name: Release in Play Store

on:
  workflow_dispatch:
    inputs:
      release_notes:
        description: 'Release Notes'
        required: true

jobs:
  determine_trigger_branch_or_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Check if Release note exists
        run: |
          if [ -f "./whatsnew/whatsnew-en-US.txt" ]; then
            echo "whatsnew-en-US.txt exists"
          else
            echo "whatsnew-en-US.txt does not exist"
            exit 1
          fi
      - name: Get latest release info
        id: latest_release
        uses: actions/github-script@v5
        with:
          script: |
            const response = await github.rest.repos.getLatestRelease({
              owner: 'SathanaV-Software-Engineer',
              repo: 'luminator_testing'
            });

            console.log('Latest release:', response.data);

            // Extract the asset details of the AAB file from the latest release
            const assetDetails = response.data.assets.find(asset => asset.name === 'app-release.aab');

            console.log('Asset details:', assetDetails.browser_download_url);
            
            // Set the assetDetails as an output
            console.log(`::set-output name=assetDetails::${assetDetails.browser_download_url}`);
      - name: Download release file
        run: |
          wget -O app-release.aab "${{ steps.latest_release.outputs.assetDetails }}"
      - name: Release app to internal track
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAYSTORE_ACCOUNT_KEY }}
          packageName: com.mobiletesting.testapp
          releaseFiles: app-release.aab
          track: internal
          status: draft
          releaseStatus: completed
          whatsNewDirectory: "./whatsnew/whatsnew-en-US.txt"
