name: Manual Trigger new now testing

on:
  workflow_dispatch:
    inputs:
      release_notes:
        description: 'Release Notes'
        required: true

jobs:
  determine_trigger_branch_or_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Print Trigger Information
        run: |
          # Extract the last segment of the ref, which corresponds to the branch or tag name
          ref_segment=$(echo "${{ github.ref }}" | awk -F'/' '{print $NF}')
          # Check if the ref_segment starts with 'refs/tags/'
          if [[ "${ref_segment}" == "refs/tags/"* ]]; then
            # If it does, then it's a tag
            tag_name="${ref_segment#"refs/tags/"}"
            echo "Triggered by tag: ${tag_name}"
          else
            # Otherwise, it's a branch
            echo "Triggered by branch: ${ref_segment}"
          fi
