name: Manual Trigger new now testing

on:
  workflow_dispatch:
    inputs:
      release_notes:
        description: 'Release Notes'
        required: true

jobs:
  # Define a job named 'build'
  build:
    # Give the job a name
    name: Build & Release
    # Specify the operating system on which the job runs
    runs-on: macos-latest

    # Define the steps to be executed in this job
    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        # Use the latest version of the checkout action to fetch the repository's code
        uses: actions/checkout@v1
      - name: Check if release note exists
        run: |
          if [ -f "./whatsnew/whatsnew-en-US" ]; then
            echo "whatsnew-en-US exists"
          else
            echo "whatsnew-en-US does not exist"
            exit 1
          fi
      - name: Read release notes from file
        id: read_release_notes
        run: |
          release_notes=$(cat ./whatsnew/whatsnew-en-US)
          printf -v formatted_notes "%s" "$release_notes"
          echo "::set-output name=release_notes::$formatted_notes"
      - name: Debug release notes content
        run: |
          cat ./whatsnew/whatsnew-en-US
          echo "End of file."
      - name: Checking output
        run: echo "${{ steps.read_release_notes.outputs.release_notes }}"
