name: Manual Trigger new now testing

on:
  workflow_dispatch:
    inputs:
      release_notes:
        description: 'Release Notes'
        required: true

jobs:
  determine_trigger_branch_or_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest release info
        uses: actions/github-script@v5
        with:
          script: |
            const response = await github.rest.repos.getLatestRelease({
              owner: 'SathanaV-Software-Engineer',
              repo: 'luminator_testing'
            });

            console.log('Latest release:', response.data);

            // Extract the asset ID of the AAB file from the latest release
            const assetDetails = response.data.assets.find(asset => asset.name === 'app-release.aab');

            console.log('Asset ID:', assetDetails.assetId);

            // You can use the asset ID to download the AAB file
            // For example, you can use curl or wget to download the file
      - name: Download AAB from URL
        run: |
          wget -O app-release.aab assetDetails.browser_download_url
    # Adjust <your-download-url> with the actual URL provided
      - name: Release app to internal track
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAYSTORE_ACCOUNT_KEY }}
          packageName: com.fluttercicddemo
          releaseFile: app-release.aab
          track: internal
          whatsNewText: ${{ github.event.inputs.release_notes }}
