name: Manual Trigger new

on:
  workflow_dispatch: # Manually trigger this workflow
     inputs:
        release_notes:
          description: 'Release Notes'
          required: true

jobs:
  print_hello:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello
      run: echo "Hello ${{ github.event.inputs.release_notes }}"
