name: Manual Trigger new now testing

on:
  workflow_dispatch:
    inputs:
      release_notes:
        description: 'Release Notes'
        required: true

jobs:
  determine_trigger_branch_or_tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Tag Name and AAB File Path
        run: |
            echo "Ref: ${github.ref}"
            if [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
              tag_name=$(echo "${{ github.ref }}" | awk -F'/' '{print $NF}')
              echo "Tag Name: ${tag_name}"
              aab_file_path="path/to/your/aab/files/${tag_name}/app-release.aab"
              echo "AAB file path: ${aab_file_path}"
        
              # Perform further operations using the AAB file path
              # For example, you can use this path in your workflow steps
            else
              echo "The trigger is not a tag."
            fi
